.PHONY: clean All

All:
	@echo "----------Building project:[ Exercise7 - Debug ]----------"
	@cd "Exercise7" && "$(MAKE)" -f  "Exercise7.mk"
clean:
	@echo "----------Cleaning project:[ Exercise7 - Debug ]----------"
	@cd "Exercise7" && "$(MAKE)" -f  "Exercise7.mk" clean
