.PHONY: clean All

All:
	@echo "----------Building project:[ Exercise6 - Debug ]----------"
	@cd "Exercise6" && "$(MAKE)" -f  "Exercise6.mk"
clean:
	@echo "----------Cleaning project:[ Exercise6 - Debug ]----------"
	@cd "Exercise6" && "$(MAKE)" -f  "Exercise6.mk" clean
